### ISSUE TITLE
autoapi hyperlinks do not work properly.

### ISSUE THREAD

**Issue by andylamp** [readthedocs/sphinx-autoapi#249] opened 2020-10-03 20:26 UTC
I have an issue when trying to link different classes to either the main `rst` documentation and cross-module within the actual function documentation.

My `conf.py` is nothing to fuzz about however the important bits for this are laid out here:

```python
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.graphviz",
    "autoapi.extension",
]

autoapi_type = "python"
BASE_PATH = os.path.abspath("../")

# get the auto api directories
autoapi_dirs = [
    os.path.join(BASE_PATH, "mymodule"),
    os.path.join(BASE_PATH, "utils"),
    os.path.join(BASE_PATH, "tests"),
]

# configure intersphinx mapping
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
```

Now, then I want to say write a documentation in `api.rst` which lies in the main `doc` directory I want to say for example

My `Class1` is inherited from `Class2` and does `X` and `Y` - I would like these to be hyperlinked throughout when someone clicks on them.

When am using `.. module:: mymodule` and then `.. autoclass mymodule.Myclass1` I can use it as normal e.g.: `:class:MyClass1 <mymodule.MyClass1>` which works as expected. However when I try to do it using the `autoapi` directives within the `rst` file it does not work - it gives me an empty link; same thing for the `docstrings` within functions - what am I doing wrong?

**Comment by AWhetter** [comment] 2020-10-08 05:40
Please could you provide a more complete example. Is there a repository somewhere that I can look at or do you have a small reproduction case? I'm not able to reproduce your issue but I don't know if I understand it fully.

**Comment by andylamp** [comment] 2020-10-08 18:37
@AWhetter hi, thanks for the reply! as for the MWE: yes - sorry; the reason not posting was that it's in a proprietary codebase that I could just copy paste; I'll produce one ASAP and I'll add it to the issue.

**Comment by AWhetter** [comment] 2021-01-31 03:37
I'm going to close this because I'm still unable to reproduce. But if you are able to come up with a reproduction case then feel free to comment and we can reopen the issue.

**Closed by AWhetter** 2021-01-31 03:37 UTC
