### ISSUE TITLE
Undocumented instance attributes are ignored even with "undoc-members" selected

### ISSUE THREAD

**Issue by hanetar** [readthedocs/sphinx-autoapi#451] opened 2024-06-10 13:02 UTC
I've found that undocumented instance attributes, e.g.:

```
class Test:
    def __init__(self):
        self.found : bool = False
````

are always left out of the documentation, regardless of the "undoc-members" setting in `autoapi_options`. They are not even sent for evaluation via the `autoapi-skip-member` callback. I don't think this is expected behavior.

As far as I can tell, this is due to line 216 in the `parse_functiondef()` method of the `Parser` class in "_parser.py":

`
result.extend(data for data in child_data if data["doc"])
`

IMO, the condition should be removed so that **all** parsed members are passed through to the filtering via `autoapi_options` and `autoapi-skip-member`, allowing the user to keep the undocumented ones as well.

**Comment by sachahu1** [comment] 2024-06-14 14:17
@hanetar I think this is a duplicate of #448 and #441. You might want to have a look at #448 To see if that solves your issue. Otherwise I've also tried to implement a fix in #453.

**Closed** 2024-06-22 01:29 UTC
Labels: Bug
