### ISSUE TITLE
[Python] `Unknown type: placeholder` error

### ISSUE THREAD

**Issue by alanhdu** [readthedocs/sphinx-autoapi#180] opened 2019-10-24 21:33 UTC
When setting up `sphinx-autoapi` for one of our internal repositories, I found a strange warning that `autoapi` would pull up:

```
WARNING: Unknown type: placeholder
```

Digging into the debugger a little bit, it turns out that this is from code like:
```
from A.B.C import (a, b, c)
from A.B.C.D import d

a1 = a
b1 = b
c1 = c

d = d   # this turns out to be a problem
```

where the debugger section shows that `d` has a `placeholder` type:

```python
[0]   /opt/anaconda/envs/ctrldev/bin/sphinx-build(10)<module>()
-> sys.exit(main())
[1]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/build.py(288)main()
-> return make_main(argv)
[2]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/build.py(195)make_main()
-> return make_mode.run_make_mode(argv[1:])
[3]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/make_mode.py(167)run_make_mode()
-> return make.run_generic_build(args[0])
[4]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/make_mode.py(155)run_generic_build()
-> return build_main(args + opts)
[5]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/cmd/build.py(275)build_main()
-> args.tags, args.verbosity, args.jobs, args.keep_going)
[6]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/application.py(269)__init__()
-> self._init_builder()
[7]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/application.py(330)_init_builder()
-> self.events.emit('builder-inited')
[8]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/sphinx/events.py(103)emit()
-> results.append(callback(self.app, *args))
[9]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/extension.py(129)run_autoapi()
-> sphinx_mapper_obj.map(options=app.config.autoapi_options)
[10]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/mappers/python/mapper.py(293)map()
-> super(PythonSphinxMapper, self).map(options)
[11] > /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/mappers/base.py(276)map()
-> for obj in self.create_class(data, options=options):
[12]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/mappers/python/mapper.py(337)create_class()
-> child_data, options=options, **kwargs
[13]   /opt/anaconda/envs/ctrldev/lib/python3.6/site-packages/autoapi/mappers/python/mapper.py(316)create_class()
-> LOGGER.warning("Unknown type: %s" % data["type"])
(Pdb++) p data['type']
'placeholder'
```

Unfortunately, I have *not* been able to reproduce this in a minimal fashion, so it's totally possible that this bug is actually some quirk of our internal code organization. Let me know if there's anything I can do to help debug!

**Comment by AWhetter** [comment] 2019-12-31 19:07
`placeholder` types are objects that have been imported from another module (https://github.com/readthedocs/sphinx-autoapi/blob/daa5ce24a587587a745b4819bb2dbe9557a0c8d4/autoapi/mappers/python/parser.py#L193). They are supposed to get resolved later on once everything has been parsed (https://github.com/readthedocs/sphinx-autoapi/blob/daa5ce24a587587a745b4819bb2dbe9557a0c8d4/autoapi/mappers/python/mapper.py#L260). So it seems that this one isn't being resolved for some reason, but I'm not sure why.
Does `A.B.C.D` define `d` in your example, or does `A.B.C.D` import `d` from somewhere else as well? At the moment we don't traverse modules in topological order when resolving placeholders (which we should change), so it might be that your example module is resolving `d`, but `A.B.C.D` still defines `d` as a placeholder that is yet to be resolved.

**Comment by alanhdu** [comment] 2020-01-02 19:23
In this case, `A.B.C.D` defines `d` (if it helps, these are `A.B.C.D` is a protocol-buffer generated file).

I took another look at our code and am still unable to come up with a nice minimal reproduction. I'm happy to close this issue if you don't think it's super actionable.

**Comment by AWhetter** [comment] 2020-01-02 19:53
I've just taken a closer look as well. I don't think my original intuition is correct because we do resolve in topological order. It seems more likely that the `d = d` is what's messing things up.

If you want to try debugging, you could place an assertion here (https://github.com/readthedocs/sphinx-autoapi/blob/daa5ce24a587587a745b4819bb2dbe9557a0c8d4/autoapi/mappers/python/mapper.py#L165) that does `assert new["type"] is not "placeholder"`. If that triggers, then modules aren't being resolved in the correct order.

**Comment by AWhetter** [comment] 2020-05-17 00:54
I've added the assertion to the code but there's nothing else I can do without more information. If you come across this again then let me know.

**Closed by AWhetter** 2020-05-17 00:54 UTC
Labels: Bug, Language: Python

**Comment by rickstaa** [comment] 2023-06-13 08:21
> I've added the assertion to the code but there's nothing else I can do without more information. If you come across this again then let me know.

Just for future reference. I got this error when I used a relative import in a python3 module. So, for me, it actually was caused by non-standard (bad) import behaviour. The issue was resolved when I changed it to an absolute import (e.g. `from test_pkg._version import __version__`).

**test_pkg/__init__.py**

```python
# Make module version available.
from ._version.py import version as __version__  # noqa: F401
from ._version.py import \
    version_tuple as __version_tuple__  # noqa: F401
```

**_version.py**

```python
# Stores the package version number so that it can be accessed from other modules.
version = "1.0.0"
version_tuple = version.split(".")
```

**Comment by rickstaa** [comment] 2023-06-13 12:28
> _resolve_placeholders

Okay, although my previous comment was in the right direction, I noticed that when I tried to create an example repository for the behaviour it didn't occur any more. This, however, led me to the real cause of the problem 😄. 

In my case, the problem was caused by the fact that I'm trying to document a [ROS](https://www.ros.org/) package. Since ROS packages have multi-language support, some python objects like Messages, Services and actions are programmatically added to the main python package using the following script:

```python
# -*- coding: utf-8 -*-
# generated from catkin/cmake/template/__init__.py.in
# keep symbol table as clean as possible by deleting all unnecessary symbols

from os import path as os_path
from pkgutil import extend_path
from sys import path as sys_path

__extended_path = '/home/ricks/Development/work/test_catkin_ws/src/test_pkg/src'.split(';')
for p in reversed(__extended_path):
    sys_path.insert(0, p)
    del p
del sys_path

__path__ = extend_path(__path__, __name__)
del extend_path

__execfiles = []
for p in __extended_path:
    src_init_file = os_path.join(p, __name__ + '.py')
    if os_path.isfile(src_init_file):
        __execfiles.append(src_init_file)
    else:
        src_init_file = os_path.join(p, __name__, '__init__.py')
        if os_path.isfile(src_init_file):
            __execfiles.append(src_init_file)
    del src_init_file
    del p
del os_path
del __extended_path

for __execfile in __execfiles:
    with open(__execfile, 'r') as __fh:
        exec(__fh.read())
    del __fh
    del __execfile
del __execfiles
```

This script is found in the [catkin](https://github.com/ros/catkin) `devel` folder, but in a folder that has the same name as the main python package. When both the main package and this catkin folder are set in the `autoapi_dirs` configuration value the
Auto-API package encounters a top `__init__.py` file twice. This use case, however, is not expected in the ` _resolve_placeholders(self):` function:

https://github.com/readthedocs/sphinx-autoapi/blob/daa5ce24a587587a745b4819bb2dbe9557a0c8d4/autoapi/mappers/python/mapper.py#L260-L270

Because of this, the second time the top `__init__.py` file is encountered, the children of the first pass are overwritten, leading to unresolved objects 😅. I created # to fix this, but am aware that this is quite a unique use case, which probably doesn't occur often when documenting python packages.

**Comment by rickstaa** [comment] 2023-06-13 12:56
@AWhetter I don't know if merging #394 is worth it, given that my use case is unique, and I cannot oversee how it affects other use cases, but I wanted to let people know why this bug occurs in most cases. There probably is an easier way to trigger this bug 🤔.

**Comment by rickstaa** [comment] 2023-06-13 12:59
I just quickly created another [simplified example repository](https://github.com/rickstaa/unknown_type_placeholder_bug/blob/main/README.md). Now it is effortless to reproduce the bug without having all the clutter ROS creates.

#### How to reproduce

1.  Clone [this example repository](https://github.com/rickstaa/unknown_type_placeholder_bug/blob/main/README.md).
2.  Install Python 3.8 (https://docs.python.org/3/).
2.  Install the venv python package (i.e. `sudo apt install python3-venv`).
3.  Create a new virtual environment using the `--system-site-packages` flag (i.e. `python3 -m venv test_pkg --system-site-packages`).
4.  Install the python dependencies (i.e. `pip install -r requirements/doc_requirements.txt`).
5.  Build the documentation from within the `docs` folder (i.e. `make html`).
6.  Be greeted by the `WARNING: Unknown type: placeholder` bug.
