### ISSUE TITLE
'env-get-updated' threw an exception when using sphinx-build -c option

### ISSUE THREAD

**Issue by sergescevenels-naspers** [readthedocs/sphinx-autoapi#254] opened 2020-11-17 11:56 UTC
when i use the following command , it works, docs get generated

`sphinx-build . ../_build/html`

however when using the -c option and thus moving the src in a different directory, an error is thrown

`sphinx-build -c . ../src  ../_build/html`

Error Message is this one : 

```
looking for now-outdated files... 
Extension error:
Handler <bound method TocTreeCollector.get_updated_docs of <sphinx.environment.collectors.toctree.TocTreeCollector object at 0x7f665ae1f910>> for event 'env-get-updated' threw an exception (exception: [Errno 2] No such file or directory: '<path>/docs/_build/html/.doctrees/reference/api/index.doctree')
```

Of course by de-activating the autoapi extension, both commands end successfully

**Comment by AWhetter** [comment] 2020-12-05 17:43
Are you able to provide a small reproduction case? I've not seen this error before.

**Comment by AWhetter** [comment] 2021-01-31 03:38
I'm going to close this because I'm still unable to reproduce. But if you are able to come up with a reproduction case then feel free to comment and we can reopen the issue.

**Closed by AWhetter** 2021-01-31 03:38 UTC
