### ISSUE TITLE
API Index does not contain subpackages or submodules names

### ISSUE THREAD

**Issue by yorickbrunet** [readthedocs/sphinx-autoapi#379] opened 2023-04-18 06:41 UTC
Hello,

I'm updated `sphinx-autoapi` from v1.8.4 to v2.1.0.
With v1.8.4, the API index was generated with subpackages and submodules names so that it was easy to select the link I wanted to follow.

Now with v2.1.0 I get
<img src="https://user-images.githubusercontent.com/2708997/232690288-aeb7d4f7-d0b8-4791-9a97-9a2df244c990.png" width="500">
There is no longer names for subpackages and submodules but only "Submodules" and "Module contents" which doesn't help much to select the right link. To be certain to switch versions correctly, I followed the [installation steps](https://github.com/readthedocs/sphinx-autoapi#getting-started).

I also tried to follow the [installation steps](https://github.com/readthedocs/sphinx-autoapi#getting-started) with another project, for which I hadn't already configured autoapi, but I get the same result.

Any idea? Is it intended or have I done a mistake somewhere?

I use:

- Sphinx==6.1.3
- sphinx-autoapi==2.1.0
- sphinx-rtd-theme==1.2.0

**Comment by AWhetter** [comment] 2023-05-22 18:17
This looks like a duplicate of #360

**Closed by AWhetter** 2023-05-22 18:17 UTC
