### ISSUE TITLE
`document isn't included in any toctree`

### ISSUE THREAD

**Issue by hblumberg** [readthedocs/sphinx-autoapi#365] opened 2023-01-30 22:20 UTC
Hello! I followed the Python tutorial [here](https://sphinx-autoapi.readthedocs.io/en/latest/tutorials.html#python) and am running into the following warning:

`checking consistency... /docs/autoapi/index.rst: WARNING: document isn't included in any toctree`

Is there any way to avoid this warning (without suppressing all warnings of this type)? Thank you!

**Comment by hblumberg** [comment] 2023-02-02 16:50
I found that adding `autoapi/index` to `index.rst` (as follows) resolved this warning without changing the document structure.

```
.. toctree::
   :maxdepth: 2
   :caption: Contents:

   autoapi/index
```

Leaving this open in case there are better approaches!

**Comment by AWhetter** [comment] 2023-04-08 02:59
This looks like a duplicate of #319, so I'll close this in favour of that issue.

**Closed by AWhetter** 2023-04-08 02:59 UTC
