### ISSUE TITLE
Dotnet: No API objects exist. Can't continue

### ISSUE THREAD

**Issue by tyuanhang** [readthedocs/sphinx-autoapi#233] opened 2020-07-27 04:01 UTC
`autoapi\mappers\dotnet.py:L92`

When executing `docfx` command to generate *.yml files, it fails because the raw file paths contain blanks.

**Comment by AWhetter** [comment] 2020-08-01 01:32
Looks like a duplicate of #79 so I'm closing this one in favour of that.

**Closed by AWhetter** 2020-08-01 01:32 UTC
