### ISSUE TITLE
ERROR: Could not import extension autoapi.sphinx (exception: No module named 'autoapi') when attempting to build docs

### ISSUE THREAD

**Issue by calebregg52** [readthedocs/sphinx-autoapi#441] opened 2024-05-06 12:41 UTC
Hello all, Im running into an issue sphinx cannot seem to locate the autoAPI extension.  For reference I used `pip install sphinx-autoapi` and I included it in the extensions list in conf.py. Im currently running python 3.10 and sphinx 5.0.0.

Any help is much appreciated!

**Comment by AWhetter** [comment] 2024-05-18 15:45
Are you doing this inside a virtualenv (https://realpython.com/python-virtual-environments-a-primer/#create-it)?

**Comment by castlez** [comment] 2024-05-23 17:59
Just another data point here, i get the same thing if i run in a venv but not if i use system python (granted i still get an error, but i think its unrelated to this issue)
Here's installing deps:
```
➜ pip install sphinx
➜ pip install sphinx_rtd_theme
➜ pip install sphinx-autoapi
```
Here's the commands
```
➜  tree .
.
├── build
│   └── _static
│       ├── jquery.js
│       └── _sphinx_javascript_frameworks_compat.js
├── code_src
│   ├── dummy.py
│   ├── __init__.py
│   └── __pycache__
│       ├── dummy.cpython-311.pyc
│       └── __init__.cpython-311.pyc
├── docs
│   ├── make.bat
│   ├── Makefile
│   └── source
│       ├── conf.py
│       └── index.rst
├── main.py
└── requirements.txt
➜  cd docs/source
➜  sphinx-build -b html . ../../build
```

and lastly here's the conf.py
```
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
templates_path = ["_templates"]
source_suffix = ".rst"
master_doc = "index"
suppress_warnings = ["autoapi"]


project = 'GitRequester'
copyright = '2024, Castle'
author = 'Castle'
release = '1.0.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'autoapi.extension',
    'sphinx.ext.viewcode'
]

autoapi_type = 'python'
autoapi_dirs = ['../../code_src']
autoapi_file_pattern = "*.py"
autoapi_options = ['members', 'private-members', 'show-inheritance',
                   'show-module-summary', 'special-members', 'imported-members', ]

exclude_patterns = ['build', 'Thumbs.db', '.DS_Store']
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
```

**Comment by AWhetter** [comment] 2024-06-20 01:06
@castlez That's a different error.
I'm closing this due to being unable to reproduce the problem, but if this is still an issue then please provide a way to reproduce and feel free to reopen.

**Closed by AWhetter** 2024-06-20 01:06 UTC
Labels: Needed: Reproduction Case

**Comment by VeckoTheGecko** [comment] 2024-12-11 18:16
I was working in a codebase where they had `"autoapi.sphinx"` instead of `"autoapi.extension"` in the extensions list. Changing to the latter fixed my issue.

Not sure if that was due to a version change or was just broken from the get go.
